### PR TITLE
Added Fish example

### PR DESCRIPTION
**Pull request by Melon-Bread**
Wanted to add another example as requested by #1 .
So I added a example for the [fish shell](https://fishshell.com/)

### CODE REVIEW

**Comment by berviantoleo** [comment]
How I can get the binary for run the script? I think it will good, if in the script put how to get the binary, you may put it in comment of the script.

**Comment by Melon-Bread** [comment]
I do not think there is a way to get a binary from a fish script, unless I am misunderstanding your request.  
It is in same vein as Bash or Batch script.

**Comment by berviantoleo** [comment]
Oh, I see. I mean, fish not installed by default in an system, yes? I mean how to get the fish. Sorry for ambigue request.

**Comment by Melon-Bread** [comment]
OH! I understand what you mean. My apologies for the confusion.  
To install the fish shell it is different for each OS. The [fish homepage](https://fishshell.com/) documents how to download & install the script for the popular OS'. So if it is okay with you I will put that in the comment line

**Comment by berviantoleo** [comment]
Ok. Great! Thanks.

**Pull request merged**
